### ISSUE TITLE
How to's for each of the custom modules and custom scripts indicating inputs required and how to run

### ISSUE THREAD

**Issue by adeslatt** [sheynkman-lab/Long-Read-Proteogenomics#1]
@cgpu asks that we add for each custom module or script a README.md - a markdown description of what to do -- one thought with all the modules is to name the readme as MODULENAME.README.md -- we can work on the asethetics later.

**Comment by trishorts** [comment]
there are readme's already in all the projects. we can try the naming convention. ben said yesterday that unless a file is named readme.md it won't show. But we can test that.

**Comment by adeslatt** [comment]
> there are readme's already in all the projects. we can try the naming convention. ben said yesterday that unless a file is named readme.md it won't show. But we can test that.

What we did with sbas is embed links - @cgpu has more experience here in her reproducibility efforts -- @cgpu what are your thoughts
