### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by trishorts** [sheynkman-lab/Long-Read-Proteogenomics#10]
Please add to this issue any items that you'd like to see added to a wiki

**Comment by trishorts** [comment]
Now that we have one, please add your comments about what you'd like to see here that would be helpful to users.

**Comment by gsheynkman** [comment]
Great - initial thoughtsDefinitely a listing of helpful links

**Comment by rmmiller22** [comment]
I think links to established tools and references would be good. As the pipeline begins to take shape, a list of all of the different input you will need, and then also a list of all of the different outputs you will receive (and why each of those is important) may be beneficial as well.

**Comment by gsheynkman** [comment]
Note to self/others as we get close to publications - what information should we have on the wiki?

**Comment by adeslatt** [comment]
Wiki will document all process and pipelines and will be pointed to from the README.md and docs will be eliminated.
