### ISSUE TITLE
Add conf/test.config with ZENODO links to data

### ISSUE THREAD

**Issue by cgpu** [sheynkman-lab/Long-Read-Proteogenomics#117]
This will enable us to store data in ZENODO and link them in the pipeline configuration files.

See more about custom configs in https://github.com/lifebit-ai/dry-bench-skills-for-researchers/blob/main/classes/class_5/1-nextflow.md#6-nextflow-custom-config-files-for-parameter-setting

**Comment by adeslatt** [comment]
@cgpu is this still important for us?

**Comment by adeslatt** [comment]
test_without_sqanti.config running with ci.test_without_sqanti.config
test_with_sqanti.confg does not yet run

test.config redundant with test_without_sqanti.config
