### ISSUE TITLE
Nextflow MetaMorpheus

### ISSUE THREAD

**Issue by bj8th** [sheynkman-lab/Long-Read-Proteogenomics#126]
An error arises when trying to implement the MetaMorpheus. This error was seen both in the latest and proteogenomic tags of the MetaMorpheus dockerfile. When running dockerfile as described in issue 94 the image runs as expected. Issue found even when script is empty, pointing to issue coming from when nextflow tries to connect to image. 

Error code : 

Error executing process > 'metamorpheus'

Caused by:
  Process `metamorpheus` terminated with an error exit status (127)

Command executed:

Command exit status:
  127

Command output:
  (empty)

Command error:
  docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.

**Comment by cgpu** [comment]
We can modify the MetaMorpheous Dockerfile a bit to copy the executable in a predictable path in the container.

```bash
.
.
.
dotnet /metamorpheus/CMD.dll
COPY metamorpheus/  /
```
