### ISSUE TITLE
Remove large file from commit history

### ISSUE THREAD

**Issue by gsheynkman** [sheynkman-lab/Long-Read-Proteogenomics#133]
@cgpu @adeslatt  and I are trying to remove a large file I accidentally pushed to main (see below).

We tried bfg (https://rtyley.github.io/bfg-repo-cleaner/) but it didn't seem to remove from the history, which is our goal.

Suggestions?!

modules/peptide_novelty_analysis/gencode.v35.pc_transcripts.fa.gz

**Comment by cgpu** [comment]
Addressed with https://github.com/sheynkman-lab/Long-Read-Proteogenomics/pull/135 and personal comm with @gsheynkman for allowing the drastical changes to git history.
