### ISSUE TITLE
missing rename_cds_to_exon.py and sqanti3_protein.py scripts

### ISSUE THREAD

**Issue by tabeariepe** [sheynkman-lab/Long-Read-Proteogenomics#157]
Hi, 

I am trying to apply your pipeline to my data. However, I am stuck because I cannot find the missing rename_cds_to_exon.py and sqanti3_protein.py scripts scripts in the modules folder. Is it possible that you also provide these scripts (or maybe there are somewhere else and I just did not see them)?

**Comment by bj8th** [comment]
Hi @tabeariepe 

The two modules were located in a different repository, https://github.com/sheynkman-lab/sqanti3-docker.
I have added them into this repo and am closing the issue.

Thanks!
