### ISSUE TITLE
git clone line issue

### ISSUE THREAD

**Issue by maallen3** [sheynkman-lab/Long-Read-Proteogenomics#159]
the line git clone https://
.com/sheynkman-lab/Long-Read-Proteogenomics
cd Long-Read-Proteogenomics seems to be incomplete.

**Comment by zappuf** [comment]
this code block was meant to be
```
git clone https://github.com/sheynkman-lab/Long-Read-Proteogenomics.git
cd Long-Read-Proteogenomics
```

**Comment by maallen3** [comment]
Thanks! Its still wrong in https://github.com/sheynkman-lab/Long-Read-Proteogenomics/wiki/Vignette-Long-Read-Proteogenomics-Workflow-with-Test-Data.

**Comment by bj8th** [comment]
Thank you for catching this. The page has been updated to reflect needed space between commands
