### ISSUE TITLE
Short read data requirement

### ISSUE THREAD

**Issue by rsalz** [sheynkman-lab/Long-Read-Proteogenomics#162]
Can this pipeline be run without short-read data? I see kallisto output from short read data is a required input of the pipeline. I only have long-read data but would still like to use this.

**Comment by gsheynkman** [comment]
Yes, the pipeline is most commonly run without short-read data input. Simply do not run the steps that require SR data. Or, input "dummy" SR data and ignore the final result of TPM values.
