### ISSUE TITLE
pNNC from NIC transcript

### ISSUE THREAD

**Issue by rsalz** [sheynkman-lab/Long-Read-Proteogenomics#167]
In my output I am finding many cases of NIC transcripts producing NNC proteins. Can you explain to me how this is possible? A ORF cannot have different/new novel junctions than the transcript it came from.

**Comment by gsheynkman** [comment]
Yes - that is because for protein-level classification, we also account for the N- and C-terminus identity. It might be a little confusing. After some discussion, we decided to denote NIC and NNC for transcripts and pNIC and pNNC for proteins.

**Comment by gsheynkman** [comment]
Please let me know if you have more questions - thank you for the inquiry. I think we may need to be a bit more clear on the "SQANTI Protein" classification for future users. tag @Sktbanerjee1
