### ISSUE TITLE
Push from Lifebit CloudOS to zenedo

### ISSUE THREAD

**Issue by rmmiller22** [sheynkman-lab/Long-Read-Proteogenomics#21]
Figure out how to programmatically upload intermediate files to zenedo and share those with the group.

**Comment by gsheynkman** [comment]
Talked with @cgpu about this - We have to manually upload to Zenodo, thus creating a new version and new DOI to represent the updated dataset.
We did figure out how to programatically download data using zenodo_g`pip3 install zenodo_get
`pip3 install zenodo_get
# to print the help message
 zenodo_get -h
# to create a txt file with all the individual file download links
# for the ZENODO repository with record 4256568
# ie https://zenodo.org/record/4256568
zenodo_get -w zenodo_download_links.txt 4256568`

**Comment by cgpu** [comment]
@gsheynkman @rmmiller22 I will look into this today as well, worth it I think.

**Comment by adeslatt** [comment]
The full REST api is in anaconda 
conda install -c conda-forge pyzenodo3

**Comment by gsheynkman** [comment]
@adeslatt Did you figure out if we can "push" to zenodo? I think the answer is no?
