### ISSUE TITLE
Append UniProt sequences for non-observed genes

### ISSUE THREAD

**Issue by rmillikin** [sheynkman-lab/Long-Read-Proteogenomics#23]
For input to MetaMorpheus. e.g., if in the pacbio data we observe transcripts transcribed from 15k genes, there are 5k genes not observed. we should take the 5k canonical uniprot protein sequences for the genes not observed and append them to the 15k we observed for a total database of 20k proteins.

**Comment by gsheynkman** [comment]
This feature should be included within the RefineDatabase module.
