### ISSUE TITLE
Delete branches and do final pull request merge so we can work with a clean slate for today

### ISSUE THREAD

**Issue by adeslatt** [sheynkman-lab/Long-Read-Proteogenomics#30]
on Sunday Nov 8 9:00 AM - I recommend we do the final pull request merge, delete all branches and start new with a fresh branch for work to be done today.

**Comment by gsheynkman** [comment]
Sounds like a great idea

**Comment by rmmiller22** [comment]
I feel a little bit weird about merging code that is still heavily under development, but that is why it would go to the dev branch and not main. Plus then we really know where we stand in terms of progress starting the day.

**Comment by cgpu** [comment]
> I feel a little bit weird about merging code that is still heavily under development, but that is why it would go to the dev branch and not main. Plus then we really know where we stand in terms of progress starting the day.

Agreed dev sounds like a good place for volatile fresh code ✔️

**Comment by cgpu** [comment]
Closed by #26
