### ISSUE TITLE
write a small script to pull all data files from zenodo

### ISSUE THREAD

**Issue by adeslatt** [sheynkman-lab/Long-Read-Proteogenomics#34]
will push this to repository after pull request gives the updated directory structure

**Comment by cgpu** [comment]
> will push this to repository after pull request gives the updated directory structure

@gsheynkman added this yesterday in Slack:
![image](https://user-images.githubusercontent.com/38183826/98480454-7217e100-21ef-11eb-90c9-63267e137d5f.png)

```
pip3 install zenodo_get
# to print the help message
 zenodo_get -h
# to create a txt file with all the individual file download links
# for the ZENODO repository with record 4256568
# ie https://zenodo.org/record/4256568
zenodo_get -w zenodo_download_links.txt 4256568
```

Suggestion: We could have this in the tutorials as it is only one command and not a script.

**Comment by gsheynkman** [comment]
Here are the commands to download all data from zenodo to your `data` directory within the repo.

```
pip3 install zenodo_get
zenodo_get -w zenodo_data_links.txt <input here the latest version, see below*>
wget -i zenodo_data_links.txt
```
*to see the latest version -> https://zenodo.org/record/4257032#.X7Gj19t7nUJ

**Comment by gsheynkman** [comment]
Note - cannot install pip3 on Lifebit CloudOS, but pip works to install zenodo_get
