### ISSUE TITLE
Filter the Uniprot-Gencode multimapping genes

### ISSUE THREAD

**Issue by gsheynkman** [sheynkman-lab/Long-Read-Proteogenomics#51]
@kyuubi430 Filter out the genes that do not have a one to one relationship between uniprot gene and gencode gene.
Note - these are likely cases in which one uniprot gene maps up to multiple genes because there are multiple copies of the gene on the genome (gencode is genome-centric.).

Report back to @rmmiller22 and @gsheynkman the fraction of genes that have this multi-mapping status. Needs to be less than 5% to proceed.

**Comment by kyuubi430** [comment]
@rmmiller22, @gsheynkman there are only ~1 (203/20921) genes in the uniprot_accession -> uniprot_gene -> gencode_gene mapping file where 1 uniprot gene maps to more than 1 gencode gene. I will filter these genes out and make a note in the peptides_analysis script.
