### ISSUE TITLE
question about where to put output files

### ISSUE THREAD

**Issue by adeslatt** [sheynkman-lab/Long-Read-Proteogenomics#58]
@cgpu where shall we put output files from our runs?  @gsheynkman should we have them echo our module structure?

**Comment by gsheynkman** [comment]
@adeslatt I am a little uncertain of what this would look like, but seems like it would make sense to have output grouped by the rough modules?
What does nextflow permanently "save" in terms of intermeidate files?  Do all files in channels get saved somewhere and what is the process for defining what files we keep?

**Comment by gsheynkman** [comment]
Found out the answer to this:

Output files during nextflow processing get written to the work directory.

**Comment by cgpu** [comment]
> Found out the answer to this:
> 
> Output files during nextflow processing get written to the work directory.
> 
> 

On this, 

`work` directory contains all intermediate files and is considered to be useful for debugging the pipeline.

`results` directory contains all the desired output files that have been declared in the `publishDir` section of the process.

So the one we look at for results is the tidy, organised `results` folder.

NOTE: 
The name `results` is not a reserved name, we can change it by defining another name in the NextFlow config file like so:

```groovy
params {
  outdir = 'not_results_but_another_name'
}

```

**Comment by gsheynkman** [comment]
This is a very clear explanation - thank you!
