### ISSUE TITLE
Migrate dockerhub images to Quay

### ISSUE THREAD

**Issue by adeslatt** [sheynkman-lab/Long-Read-Proteogenomics#86]
Given the new DockerHub pull limits, it does not lend itself to the model used in GitHub https://www.openshift.com/blog/mitigate-impact-of-docker-hub-pull-request-limits.  We need to move to Quay

**Comment by gsheynkman** [comment]
@cgpu or @adeslatt Where your students in the class using Quay and/or do you have a tutorial or suggestion for how we set this up? If not, I'm happy to be the guinea pig.

**Comment by cgpu** [comment]
> @cgpu or @adeslatt Where your students in the class using Quay and/or do you have a tutorial or suggestion for how we set this up? If not, I'm happy to be the guinea pig.

@gsheynkman I will prepare docs for tomorrow for this 👍

**Comment by gsheynkman** [comment]
Sounds good!
